### ISSUE TITLE
openxc-enabler-5.3.1 version can't receive message from simulator

### ISSUE THREAD

**Issue by guanglixiang** [openxc/openxc-vehicle-simulator#34]
when  lunch the web application in firefox and start openxc-enabler-5.3.1 application.
 The connection between web and android client have establish。
but android client receive null data.

**Comment by AbdelhediAhmed** [comment]
good evening,
i would like to ask you about how to extract json file from simulator OpenXC in real time and used it as a data source of openXC enabled
thanks for you help

**Comment by zacnelson** [comment]
@AbdelhediAhmed here is the webpage documentation for the simulator: http://openxcplatform.com/projects/simulator.html. 

All you need to do is run the simulator and then follow the instructions in the "Running the Simulator" section: 

> To connect with an Android device, open the Enabler activity, open the settings, choose Data Sources, and enable "Use a network device".
