### ISSUE TITLE
export data

### ISSUE THREAD

**Issue by essramos** [openxc/openxc-vehicle-simulator#41]
is there any way to export the data aside from it being displayed on the UI and android device?

**Comment by emarsman** [comment]
Yes, OpenXC has trace files that are logs of data. Examples: http://openxcplatform.com/resources/traces.html. You can turn this on in Enabler->Settings->Recordings. 

So you could connect to Enabler and then record there. This isn't supported directly in the python in the simulator. But you can make your own log by sticking it in here: https://github.com/openxc/openxc-vehicle-simulator/blob/master/enabler_connection.py#L18. 

Regards,
Eric

**Comment by essramos** [comment]
thanks! is it possible to connect to enabler without using anddroid phone?

**Comment by emarsman** [comment]
Enabler is the OpenXC app that runs on Android devices so there really isn't another way. You could try Android emulators, but I'm not sure how well they will manage the network connections compared to a real device.
